using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using System;

public class GameInput : MonoBehaviour
{
    //Interaction event using a delegate type. 
    public event EventHandler OnInteractAction;

    //contstruct the script class that was autogenerated. 
    private PlayerInputActions playerInputActions;
   


    private void Awake()
    {
        //create an object of the type player
        playerInputActions = new PlayerInputActions();
        playerInputActions.Player.Enable();

        //interacting 
        playerInputActions.Player.Interact.performed += Interact_performed;// not calling the function but passing it as a refrence. 

    }

    // when the player presses the interact action, it will cal this event. 
    private void Interact_performed(InputAction.CallbackContext obj)
    {
        //ask if there are listners is one options (Using an f statment
        //using ? is a null onditional operator. It basically operates from the right, when it gets to a question mark,
        //it will evaluate the left side and if it is null it will not throw errors
        //invoke is here because a question mark cannot call a function. 
        OnInteractAction?.Invoke(this, EventArgs.Empty);

    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    public Vector2 GetMovementVector()
    {
        //this reads the vector2 that was made in the Player Action Map and can be used in the script
        Vector2 inputVector = playerInputActions.Player.Move.ReadValue<Vector2>();

        //you can also normalize the code through the PlayerInputAvtions menue
        //normalize the vector to ensure consistent speed
        inputVector = inputVector.normalized;

        return inputVector;
    

    }
}
